{% set name = "chunky3d" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 912ac315bfabdcdfd451b8e050fefe36705e5aa5fd6a6519ba14919f01ccbbca


build:
  number: 1
  skip: true  # [py27]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dill
    - msgpack-numpy
    - msgpack-python
    - numba
    - psutil
    - scipy

test:
  requires:
    - itk
    - nose
    - networkx
    - simpleitk
    - vtk
  source_files:
    - test/*.py
  commands:
    - nosetests

about:
  home: https://github.com/K3D-tools/chunky3d
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A 3D array-like NumPy-based data structure for large sparsely-populated volumes

  description: |
    chunky3d provides a 3D array-like NumPy-based data structure for large 
    sparsely-populated volumes, chunky3d.Sparse, along with some algorithms for
    processing integer masks (morhpology) or volumetric data (spacial interpolation).
  # TODO: create an publish documentation.
  # doc_url: https://chunky3d.readthedocs.io/
  dev_url: https://github.com/K3D-tools/chunky3d

extra:
  recipe-maintainers:
    - artur-trzesiok
    - tgandor
