{% set name = "chunky3d" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f734fcae113445e2b17e54eb525c22785766b9af776473c870b928a4d264f0a


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dill
    - msgpack-numpy
    - msgpack-python
    - numba
    - psutil
    - scikit-image
    - scipy

test:
  requires:
    - itk
    - networkx
    - nose
    - pip
    - simpleitk  # [unix]
    - vtk
  source_files:
    - test/*.py
  commands:
    - nosetests

about:
  home: https://github.com/K3D-tools/chunky3d
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A 3D array-like NumPy-based data structure for large sparsely-populated volumes

  description: |
    chunky3d provides a 3D array-like NumPy-based data structure for large 
    sparsely-populated volumes, chunky3d.Sparse, along with some algorithms for
    processing integer masks (morhpology) or volumetric data (spatial interpolation).
  # TODO: create an publish documentation.
  # doc_url: https://chunky3d.readthedocs.io/
  dev_url: https://github.com/K3D-tools/chunky3d

extra:
  recipe-maintainers:
    - artur-trzesiok
    - tgandor
