travis:
  secure:
    BINSTAR_TOKEN: JZtxubxVThrE1KOr4vMIt0rVw9d88J5Zxo5hyDMbe1SJD3hfpymUNRc3xiZKP3am0wlhCJGXI6CpUzIkVq7wgJBGOHzXstLqAz/HhcpQhY5wUROVuhpqGPXhZUirRqggrhXOAQOEr7adWCDyUDz6L2pqjzunD1bL8XP/3x5l9FUagp8Qw489Gu02hdrSgMNnwUwZCLJk4V+8i2q2VZ0xxot1hEbKgYX2e8g/9820xJZBzAf/mEpCFUkd+YE7A92XFV5UaAAZ1b4h0SmmT5jOxy8gG68mKVmaSiOgU1pVTchvARQ00o+vHevOtQ30LVJVtfobjuxNa/hy7QSKkFabvmCJpUO+ZdP4w4y1LSw+NiASOrq84iqstqrcwTEn+s6JQyYsjQzMd8cWPnAtC/dglejh6CAn8jJAoN4Mj3ePpeD1FWHljYzavUmxoH3xEBj0MH+RjyPKJ32QGd0mEhmKa8eDxVyyjAmvPMjKJatJ47AXYpXvc1tnjOQxJeqxk4atj5IwUZqsNBwR5iNxecNvf+t6hsHzLmMBWUM3y45Qp7zjalP2nfGK8gWWfqC6fCqlN5mTkwdElBvbED5dHUUaHUAehS44T60cYd6HZEbCS5UIcUWkz4B+OqHs3OD/y+AEFs4RP410B3969wpNuv6N0SiFuGNbg2F+dBehBoKaLCA=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
